"""add religion column to user

Revision ID: 2f3cf5cf5dcc
Revises: a6a42ad1ecda
Create Date: 2025-05-20 08:33:59.765633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3cf5cf5dcc'
down_revision = 'a6a42ad1ecda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('religion', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('religion')

    # ### end Alembic commands ###
