"""Initial migration with ijazah and kk columns

Revision ID: 417c73ba7b72
Revises: 
Create Date: 2025-05-14 10:50:48.605801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417c73ba7b72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ijazah', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('kk', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ijazah_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('kk_confirmed', sa.Boolean(), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('hobby',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('hobby',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('kk_confirmed')
        batch_op.drop_column('ijazah_confirmed')
        batch_op.drop_column('kk')
        batch_op.drop_column('ijazah')

    # ### end Alembic commands ###
