"""Add is_action_taken and is_payment_action_taken columns to User

Revision ID: 5488d44bdbae
Revises: dd38a86eef98
Create Date: 2025-05-15 11:00:07.406396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5488d44bdbae'
down_revision = 'dd38a86eef98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_action_taken', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_payment_action_taken', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_payment_action_taken')
        batch_op.drop_column('is_action_taken')

    # ### end Alembic commands ###
