"""Update notification model

Revision ID: 8d88b0c162f0
Revises: 2f3cf5cf5dcc
Create Date: 2025-05-21 09:31:29.310044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d88b0c162f0'
down_revision = '2f3cf5cf5dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('reason')
        batch_op.drop_column('action')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
