"""add faculty to user

Revision ID: a6a42ad1ecda
Revises: 5488d44bdbae
Create Date: 2025-05-19 08:38:32.987839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a42ad1ecda'
down_revision = '5488d44bdbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('faculty')

    # ### end Alembic commands ###
