"""Add payment_status and payment_proof to user

Revision ID: dd38a86eef98
Revises: 417c73ba7b72
Create Date: 2025-05-15 10:20:50.117437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd38a86eef98'
down_revision = '417c73ba7b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_proof', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('payment_proof')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
